### PR TITLE
Add Schaathun's "split sequences"

### PR DESCRIPTION
**Pull request by curiousleo**
These sequence were created by Schaathun to detect correlations between generators produced by `split`. I thought they might be a useful addition to the existing `laggedsplit` and `treesplits` functions.

The paper assumes that `split` is a pure function, i.e. `gL, gR = split g` splits `g` into the "left" generator `gL` and the "right" generator `gR`. Here, `Maketest` operators on stateful generators, so it's `g' = split g` which creates `g'` and modifies `g`.

For the sake of using the paper's notation, I arbitrarily decided to call `g'` the "right" generator and the modified `g` the "left" generator. Hence the annotations in the code of the form `gR = split g (* now gL = g *)`.

Paper: https://doi.org/10.1017/S095679681500012X
Blog post with diagrams: https://www.tweag.io/blog/2020-06-29-prng-test/
Haskell implementation: [generate/Main.hs](https://github.com/tweag/random-quality/blob/de49828bde2cf4fd9ab1ce30d57722523461862a/generate/Main.hs#L52-L116)

### CODE REVIEW

**Comment by curiousleo** [comment]
PractRand results for LXM so far:

```
test/generator.exe -splitl -lxm -seed 42 | RNG_test stdin32
RNG_test using PractRand version 0.93
RNG = RNG_stdin32, seed = 0xc8d66ab
test set = normal, folding = standard (32 bit)

rng=RNG_stdin32, seed=0xc8d66ab
length= 256 megabytes (2^28 bytes), time= 3.3 seconds
  Test Name                         Raw       Processed     Evaluation
  [Low1/32]FPF-14+6/16:all          R=  +5.0  p =  3.8e-4   unusual          
  ...and 123 test result(s) without anomalies

rng=RNG_stdin32, seed=0xc8d66ab
length= 512 megabytes (2^29 bytes), time= 6.7 seconds
  no anomalies in 132 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 1 gigabyte (2^30 bytes), time= 13.6 seconds
  no anomalies in 141 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 2 gigabytes (2^31 bytes), time= 27.7 seconds
  Test Name                         Raw       Processed     Evaluation
  DC6-9x1Bytes-1                    R=  -3.8  p =1-8.8e-3   unusual          
  ...and 147 test result(s) without anomalies

rng=RNG_stdin32, seed=0xc8d66ab
length= 4 gigabytes (2^32 bytes), time= 55.7 seconds
  no anomalies in 156 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 8 gigabytes (2^33 bytes), time= 112 seconds
  Test Name                         Raw       Processed     Evaluation
  [Low8/32]BCFN(2+1,13-0,T)         R=  +8.0  p =  8.1e-4   unusual          
  ...and 164 test result(s) without anomalies

rng=RNG_stdin32, seed=0xc8d66ab
length= 16 gigabytes (2^34 bytes), time= 228 seconds
  no anomalies in 172 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 32 gigabytes (2^35 bytes), time= 452 seconds
  no anomalies in 180 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 64 gigabytes (2^36 bytes), time= 911 seconds
  no anomalies in 189 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 128 gigabytes (2^37 bytes), time= 1827 seconds
  no anomalies in 196 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 256 gigabytes (2^38 bytes), time= 3623 seconds
  no anomalies in 204 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 512 gigabytes (2^39 bytes), time= 7261 seconds
  no anomalies in 213 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 1 terabyte (2^40 bytes), time= 14500 seconds
  no anomalies in 220 test result(s)

rng=RNG_stdin32, seed=0xc8d66ab
length= 2 terabytes (2^41 bytes), time= 28826 seconds
  no anomalies in 228 test result(s)
```

```
test/generator.exe -splitr -lxm -seed 42 | RNG_test stdin32
RNG_test using PractRand version 0.93
RNG = RNG_stdin32, seed = 0xca1478cd
test set = normal, folding = standard (32 bit)

rng=RNG_stdin32, seed=0xca1478cd
length= 256 megabytes (2^28 bytes), time= 3.4 seconds
  Test Name                         Raw       Processed     Evaluation
  DC6-9x1Bytes-1                    R=  -3.6  p = 0.988     unusual          
  ...and 123 test result(s) without anomalies

rng=RNG_stdin32, seed=0xca1478cd
length= 512 megabytes (2^29 bytes), time= 6.9 seconds
  no anomalies in 132 test result(s)

rng=RNG_stdin32, seed=0xca1478cd
length= 1 gigabyte (2^30 bytes), time= 14.2 seconds
  Test Name                         Raw       Processed     Evaluation
  [Low1/32]BCFN(2+0,13-4,T)         R=  -6.2  p =1-1.8e-3   unusual          
  ...and 140 test result(s) without anomalies

rng=RNG_stdin32, seed=0xca1478cd
length= 2 gigabytes (2^31 bytes), time= 28.8 seconds
  no anomalies in 148 test result(s)

rng=RNG_stdin32, seed=0xca1478cd
length= 4 gigabytes (2^32 bytes), time= 56.8 seconds
  Test Name                         Raw       Processed     Evaluation
  FPF-14+6/16:cross                 R=  -2.2  p =1-9.4e-4   unusual          
  ...and 155 test result(s) without anomalies

rng=RNG_stdin32, seed=0xca1478cd
length= 8 gigabytes (2^33 bytes), time= 114 seconds
  Test Name                         Raw       Processed     Evaluation
  FPF-14+6/16:cross                 R=  -2.2  p =1-9.3e-4   unusual          
  ...and 164 test result(s) without anomalies

rng=RNG_stdin32, seed=0xca1478cd
length= 16 gigabytes (2^34 bytes), time= 230 seconds
  no anomalies in 172 test result(s)

rng=RNG_stdin32, seed=0xca1478cd
length= 32 gigabytes (2^35 bytes), time= 456 seconds
  no anomalies in 180 test result(s)

rng=RNG_stdin32, seed=0xca1478cd
length= 64 gigabytes (2^36 bytes), time= 920 seconds
  no anomalies in 189 test result(s)

rng=RNG_stdin32, seed=0xca1478cd
length= 128 gigabytes (2^37 bytes), time= 1842 seconds
  no anomalies in 196 test result(s)

rng=RNG_stdin32, seed=0xca1478cd
length= 256 gigabytes (2^38 bytes), time= 3652 seconds
  Test Name                         Raw       Processed     Evaluation
  [Low1/32]Gap-16:A                 R=  +4.9  p =  1.4e-3   unusual          
  ...and 203 test result(s) without anomalies

rng=RNG_stdin32, seed=0xca1478cd
length= 512 gigabytes (2^39 bytes), time= 7316 seconds
  no anomalies in 213 test result(s)

rng=RNG_stdin32, seed=0xca1478cd
length= 1 terabyte (2^40 bytes), time= 14609 seconds
  no anomalies in 220 test result(s)

rng=RNG_stdin32, seed=0xca1478cd
length= 2 terabytes (2^41 bytes), time= 29042 seconds
  no anomalies in 228 test result(s)
```

```
test/generator.exe -splita -lxm -seed 42 | RNG_test stdin32
RNG_test using PractRand version 0.93
RNG = RNG_stdin32, seed = 0x36525a3
test set = normal, folding = standard (32 bit)

rng=RNG_stdin32, seed=0x36525a3
length= 256 megabytes (2^28 bytes), time= 3.4 seconds
  no anomalies in 124 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 512 megabytes (2^29 bytes), time= 7.1 seconds
  no anomalies in 132 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 1 gigabyte (2^30 bytes), time= 14.3 seconds
  no anomalies in 141 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 2 gigabytes (2^31 bytes), time= 28.4 seconds
  no anomalies in 148 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 4 gigabytes (2^32 bytes), time= 56.4 seconds
  no anomalies in 156 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 8 gigabytes (2^33 bytes), time= 113 seconds
  no anomalies in 165 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 16 gigabytes (2^34 bytes), time= 227 seconds
  no anomalies in 172 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 32 gigabytes (2^35 bytes), time= 452 seconds
  no anomalies in 180 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 64 gigabytes (2^36 bytes), time= 912 seconds
  no anomalies in 189 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 128 gigabytes (2^37 bytes), time= 1828 seconds
  no anomalies in 196 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 256 gigabytes (2^38 bytes), time= 3623 seconds
  Test Name                         Raw       Processed     Evaluation
  Gap-16:B                          R=  +4.1  p =  2.0e-3   unusual          
  [Low1/32]BCFN(2+3,13-0,T)         R=  -7.8  p =1-4.8e-4   unusual          
  ...and 202 test result(s) without anomalies

rng=RNG_stdin32, seed=0x36525a3
length= 512 gigabytes (2^39 bytes), time= 7260 seconds
  Test Name                         Raw       Processed     Evaluation
  BCFN(2+0,13-0,T)                  R=  -7.0  p =1-1.7e-3   unusual          
  ...and 212 test result(s) without anomalies

rng=RNG_stdin32, seed=0x36525a3
length= 1 terabyte (2^40 bytes), time= 14491 seconds
  no anomalies in 220 test result(s)

rng=RNG_stdin32, seed=0x36525a3
length= 2 terabytes (2^41 bytes), time= 28813 seconds
  no anomalies in 228 test result(s)
```

```
test/generator.exe -splits -lxm -seed 42 | RNG_test stdin32
RNG_test using PractRand version 0.93
RNG = RNG_stdin32, seed = 0x680179c
test set = normal, folding = standard (32 bit)

rng=RNG_stdin32, seed=0x680179c
length= 256 megabytes (2^28 bytes), time= 3.3 seconds
  no anomalies in 124 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 512 megabytes (2^29 bytes), time= 6.7 seconds
  no anomalies in 132 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 1 gigabyte (2^30 bytes), time= 13.4 seconds
  no anomalies in 141 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 2 gigabytes (2^31 bytes), time= 26.7 seconds
  no anomalies in 148 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 4 gigabytes (2^32 bytes), time= 54.5 seconds
  no anomalies in 156 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 8 gigabytes (2^33 bytes), time= 112 seconds
  no anomalies in 165 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 16 gigabytes (2^34 bytes), time= 227 seconds
  no anomalies in 172 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 32 gigabytes (2^35 bytes), time= 453 seconds
  no anomalies in 180 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 64 gigabytes (2^36 bytes), time= 915 seconds
  Test Name                         Raw       Processed     Evaluation
  BCFN(2+2,13-0,T)                  R=  +7.4  p =  1.7e-3   unusual          
  [Low1/32]Gap-16:B                 R=  +4.3  p =  1.3e-3   unusual          
  ...and 187 test result(s) without anomalies

rng=RNG_stdin32, seed=0x680179c
length= 128 gigabytes (2^37 bytes), time= 1836 seconds
  no anomalies in 196 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 256 gigabytes (2^38 bytes), time= 3644 seconds
  no anomalies in 204 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 512 gigabytes (2^39 bytes), time= 7306 seconds
  no anomalies in 213 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 1 terabyte (2^40 bytes), time= 14587 seconds
  no anomalies in 220 test result(s)

rng=RNG_stdin32, seed=0x680179c
length= 2 terabytes (2^41 bytes), time= 29008 seconds
  no anomalies in 228 test result(s)
```

**Review by xavierleroy — APPROVED** [review]
Thanks for the additional tests.  Will run them through Dieharder soon.

**Comment by xavierleroy** [comment]
Dieharder reports nothing unusual with the 4 "split" tests, neither for LXM, Splitmix, nor Chacha.

**Comment by curiousleo** [comment]
> Dieharder reports nothing unusual with the 4 "split" tests, neither for LXM, Splitmix, nor Chacha.

It's good to have that confirmation.

It feels like a bit of a game of whack-a-mole -- Schaathun created these sequence specifically to show that Haskell's `split` at the time was of low quality -- but at least we can automate the whack-a-mole to some degree so past mistakes are not repeated.

**Pull request merged**
